# -*- coding: utf-8 -*-
from phogo import *

print("DISTANCE", end='')
distance()
print("FORWARD", end='')
forward()
forward(30)    
forward(units=40)    
print("BACKWARD", end='')
backward()
backward(30)    
backward(units=40)
print("RIGHT", end='')
right()
right(180)    
right(degrees=360)
print("LEFT", end='')
left()
left(180)    
left(degrees=360)
print("PEN_UP", end='')
pen_up()
print("PEN_DOWN", end='')
pen_down()
